# Generated by Django 4.2.8 on 2023-12-21 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('idcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='工号')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('0', '女')], max_length=2, null=True, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号码')),
                ('admin_level', models.IntegerField(default=0, verbose_name='权限等级')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('idcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='楼宇编码')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='楼宇名称')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('points', models.CharField(blank=True, max_length=200, null=True, verbose_name='位置点坐标')),
                ('center_point', models.CharField(blank=True, max_length=50, null=True, verbose_name='位置中点')),
                ('elec', models.BooleanField(default=False, verbose_name='独立供电')),
                ('wifi', models.BooleanField(default=False, verbose_name='wifi覆盖')),
                ('dhcp', models.BooleanField(default=False, verbose_name='启用DHCP')),
                ('ipv6', models.BooleanField(default=False, verbose_name='启用IPV6')),
                ('eduroam', models.BooleanField(default=False, verbose_name='启用eduroam')),
                ('date_update', models.DateField(blank=True, null=True, verbose_name='有线网络改造时间')),
                ('date2_update', models.DateField(blank=True, null=True, verbose_name='无线网络改造时间')),
                ('num_wireless', models.IntegerField(blank=True, null=True, verbose_name='无线点位数')),
                ('num_wired', models.IntegerField(blank=True, null=True, verbose_name='有线点位数')),
            ],
            options={
                'verbose_name': '楼宇表',
                'verbose_name_plural': '楼宇表',
                'db_table': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('idcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='校区编码')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='校区名称')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校区表',
                'verbose_name_plural': '校区表',
                'db_table': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='管理IP')),
                ('name', models.CharField(max_length=100, verbose_name='品牌')),
                ('version', models.CharField(max_length=100, verbose_name='型号')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('vacant1', models.IntegerField(default=0, verbose_name='剩余网口数量')),
                ('vacant2', models.IntegerField(default=0, verbose_name='剩余光口数量')),
                ('cabinet', models.IntegerField(default=1, verbose_name='所在机柜')),
                ('index', models.IntegerField(default=0, verbose_name='所在位置xU')),
            ],
            options={
                'verbose_name': '设备表',
                'verbose_name_plural': '设备表',
                'db_table': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Dic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='键')),
                ('value', models.CharField(max_length=10, verbose_name='值')),
                ('type', models.CharField(max_length=10, verbose_name='分类')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '字典表',
                'verbose_name_plural': '字典表',
                'db_table': 'Dic',
            },
        ),
        migrations.CreateModel(
            name='DK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='线路名')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('num', models.FloatField(blank=True, null=True, verbose_name='带宽')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '带宽表',
                'verbose_name_plural': '带宽表',
                'db_table': 'DK',
            },
        ),
        migrations.CreateModel(
            name='FZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='负载名')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '负载表',
                'verbose_name_plural': '负载表',
                'db_table': 'FZ',
            },
        ),
        migrations.CreateModel(
            name='GX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='段落名')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='长度')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '光纤表',
                'verbose_name_plural': '光纤表',
                'db_table': 'GX',
            },
        ),
        migrations.CreateModel(
            name='IPnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('network', models.CharField(max_length=200, verbose_name='network')),
                ('netmask', models.CharField(max_length=200, verbose_name='netmask')),
                ('netmask_int', models.IntegerField(verbose_name='netmask_int')),
                ('free', models.BooleanField(default=False, verbose_name='免认证')),
            ],
            options={
                'verbose_name': 'IPnetmask表',
                'verbose_name_plural': 'IPnetmask表',
                'db_table': 'IPnet',
            },
        ),
        migrations.CreateModel(
            name='JF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='机房信息')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='面积')),
                ('area2', models.FloatField(blank=True, null=True, verbose_name='面积2')),
                ('ups', models.FloatField(blank=True, null=True, verbose_name='UPS时间东')),
                ('ups2', models.FloatField(blank=True, null=True, verbose_name='UPS时间西')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机房信息表',
                'verbose_name_plural': '机房信息表',
                'db_table': 'JF',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='预计开始日期')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='预计完成日期')),
                ('detail', models.TextField(verbose_name='任务描述')),
                ('done', models.BooleanField(default=False, help_text='结了尾款才是完成', verbose_name='是否完成')),
                ('date_remain', models.DateField(blank=True, null=True, verbose_name='预计支付尾款日期')),
                ('always', models.BooleanField(default=False, verbose_name='是否每年例行')),
                ('dic_tasks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dic_tasks', to='web_source.dic', verbose_name='任务所在年度')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='任务负责人')),
            ],
            options={
                'verbose_name': '工作任务表',
                'verbose_name_plural': '工作任务表',
                'db_table': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0, unique=True, verbose_name='vlan')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Vlan表',
                'verbose_name_plural': 'Vlan表',
                'db_table': 'Vlan',
            },
        ),
        migrations.CreateModel(
            name='VLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings_vlinks', to='web_source.buildings', verbose_name='楼宇')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlan_vlinks', to='web_source.vlan', verbose_name='Vlan')),
            ],
            options={
                'verbose_name': 'VlanBuilding关联表',
                'verbose_name_plural': 'VlanBuilding关联表',
                'db_table': 'VLinks',
            },
        ),
        migrations.CreateModel(
            name='TLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(verbose_name='简单描述')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_tlinks', to='web_source.tasks', verbose_name='任务名称')),
            ],
            options={
                'verbose_name': 'task的其他追加信息表',
                'verbose_name_plural': 'task的其他追加信息表',
                'db_table': 'TLinks',
            },
        ),
        migrations.CreateModel(
            name='Systerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='系统名称')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('date_run', models.DateField(verbose_name='上线日期')),
                ('ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='远程端口')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作系统')),
                ('plus', models.TextField(blank=True, null=True, verbose_name='插件名称及版本')),
                ('dic_systerms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_systerms', to='web_source.dic', verbose_name='分类')),
            ],
            options={
                'verbose_name': '管理系统表',
                'verbose_name_plural': '管理系统表',
                'db_table': 'Systerms',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='房间名称')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('remarks2', models.TextField(blank=True, max_length=100, null=True, verbose_name='其他备注')),
                ('important', models.BooleanField(default=False, verbose_name='重点节点')),
                ('core', models.BooleanField(default=False, verbose_name='核心节点')),
                ('conver', models.BooleanField(default=False, verbose_name='汇聚节点')),
                ('vacant', models.IntegerField(default=0, verbose_name='下连剩余光纤口数量')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings_rooms', to='web_source.buildings', verbose_name='所在楼宇')),
                ('dic_rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_rooms', to='web_source.dic', verbose_name='类型')),
            ],
            options={
                'verbose_name': '设备间表',
                'verbose_name_plural': '设备间表',
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('vacant', models.IntegerField(default=0, verbose_name='剩余光纤口数量')),
                ('current_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_rooms', to='web_source.rooms', verbose_name='当前房间')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_rooms', to='web_source.rooms', verbose_name='上连房间')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_rooms', to='web_source.rooms', verbose_name='下连房间')),
            ],
            options={
                'verbose_name': '设备间连通表',
                'verbose_name_plural': '设备间连通表',
                'db_table': 'RLinks',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='日志名称')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('dic_notes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dic_notes', to='web_source.dic', verbose_name='分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_notes', to=settings.AUTH_USER_MODEL, verbose_name='撰写人')),
            ],
            options={
                'verbose_name': '工作日志表',
                'verbose_name_plural': '工作日志表',
                'db_table': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='IPspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('ip', models.CharField(max_length=200, verbose_name='IP')),
                ('dic_ipspecial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_ipspecial', to='web_source.dic', verbose_name='固定、免认证')),
                ('ipnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipnet_ipspecial', to='web_source.ipnet', verbose_name='所在IP名')),
            ],
            options={
                'verbose_name': '特殊IP表',
                'verbose_name_plural': '特殊IP表',
                'db_table': 'IPspecial',
            },
        ),
        migrations.AddField(
            model_name='ipnet',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlan_ipnet', to='web_source.vlan', verbose_name='所属Vlan'),
        ),
        migrations.CreateModel(
            name='DLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('index', models.IntegerField(default=0, verbose_name='端口号')),
                ('current_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_devices', to='web_source.devices', verbose_name='当前设备')),
                ('from_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_devices', to='web_source.devices', verbose_name='上连设备')),
                ('to_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_devices', to='web_source.devices', verbose_name='下连设备')),
            ],
            options={
                'verbose_name': '设备连通表',
                'verbose_name_plural': '设备连通表',
                'db_table': 'DLinks',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='dic_devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_devices', to='web_source.dic', verbose_name='类型AC\\AM\\SWITCH\\ROUTE\\OTHER'),
        ),
        migrations.AddField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms_devices', to='web_source.rooms', verbose_name='所在房间'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings_campus', to='web_source.campus', verbose_name='校区'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='dic_buildings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_buildings', to='web_source.dic', verbose_name='介质类型'),
        ),
        migrations.CreateModel(
            name='Bigthings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='事件名称')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('charge', models.CharField(max_length=20, verbose_name='当时单位负责人')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('date_happen', models.DateField(verbose_name='发生日期')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='Bigthings', verbose_name='事件图片')),
                ('specs', models.FileField(blank=True, null=True, upload_to='Bigthings', verbose_name='事件附件')),
                ('dic_bigthings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_bigthings', to='web_source.dic', verbose_name='分类')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_bigthings', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': '大事件表',
                'verbose_name_plural': '大事件表',
                'db_table': 'Bigthings',
            },
        ),
    ]
