# Generated by Django 4.2.8 on 2023-12-21 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='dic_devices_j',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_devices2', to='web_source.dic', verbose_name='介质类型有线\\无线\\有线无线一体'),
        ),
    ]
