# Generated by Django 4.2.8 on 2023-12-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0002_devices_dic_devices_j'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipnet',
            name='ipnetmask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlan_ipnetmask', to='web_source.dic', verbose_name='分类描述'),
        ),
        migrations.AddField(
            model_name='ipnet',
            name='ipvlanloc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_ipvlanloc', to='web_source.dic', verbose_name='所属核心'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='dic_devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_devices', to='web_source.dic', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='dic_devices_j',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_devices2', to='web_source.dic', verbose_name='介质类型'),
        ),
    ]
