# Generated by Django 4.2.8 on 2023-12-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0003_ipnet_ipnetmask_ipnet_ipvlanloc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipnet',
            old_name='ipvlanloc',
            new_name='dic_ipvlanloc',
        ),
        migrations.RemoveField(
            model_name='ipnet',
            name='ipnetmask',
        ),
        migrations.AddField(
            model_name='ipnet',
            name='dic_ipnetmask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dic_ipnetmask', to='web_source.dic', verbose_name='分类描述'),
        ),
    ]
