# Generated by Django 4.2.8 on 2023-12-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0004_rename_ipvlanloc_ipnet_dic_ipvlanloc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipnet',
            name='supervlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlan_ipnet_supervlan', to='web_source.vlan', verbose_name='supervlan'),
        ),
    ]
