# Generated by Django 4.2.8 on 2023-12-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0006_remove_ipnet_supervlan_ipnet_supervlan_is_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipnet',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings_ipnet', to='web_source.buildings', verbose_name='楼宇'),
        ),
    ]
