# Generated by Django 4.2.8 on 2023-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0007_ipnet_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnet',
            name='free',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='免认证'),
        ),
        migrations.AlterField(
            model_name='ipnet',
            name='supervlan_is',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='supervlan'),
        ),
    ]
