# Generated by Django 4.2.8 on 2023-12-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0008_alter_ipnet_free_alter_ipnet_supervlan_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnet',
            name='netmask',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='netmask'),
        ),
        migrations.AlterField(
            model_name='ipnet',
            name='netmask_int',
            field=models.IntegerField(blank=True, null=True, verbose_name='netmask_int'),
        ),
        migrations.AlterField(
            model_name='ipnet',
            name='network',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='network'),
        ),
    ]
