# Generated by Django 4.2.8 on 2025-03-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0009_alter_ipnet_netmask_alter_ipnet_netmask_int_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='points',
        ),
        migrations.AddField(
            model_name='buildings',
            name='point1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置点坐标1'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='point2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置点坐标1'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='point3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置点坐标2'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='point4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置点坐标2'),
        ),
    ]
