# Generated by Django 4.2.8 on 2025-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0010_remove_buildings_points_buildings_point1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='point2',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='point3',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='point4',
        ),
        migrations.AddField(
            model_name='buildings',
            name='points',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置点坐标'),
        ),
    ]
