# Generated by Django 4.2.8 on 2025-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0011_remove_buildings_point1_remove_buildings_point2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systerms',
            name='date_gb',
            field=models.DateField(blank=True, null=True, verbose_name='过保日期'),
        ),
        migrations.AlterField(
            model_name='systerms',
            name='date_run',
            field=models.DateField(blank=True, null=True, verbose_name='上线日期'),
        ),
    ]
