# Generated by Django 4.2.8 on 2025-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0012_systerms_date_gb_alter_systerms_date_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='systerms',
            name='ssl',
            field=models.BooleanField(default=False, verbose_name='使用SSL证书'),
        ),
    ]
