# Generated by Django 4.2.8 on 2025-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0013_systerms_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='systerms',
            name='wk',
            field=models.BooleanField(default=False, verbose_name='续保有尾款'),
        ),
    ]
