# Generated by Django 4.2.8 on 2025-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0014_systerms_wk'),
    ]

    operations = [
        migrations.AddField(
            model_name='systerms',
            name='use',
            field=models.CharField(blank=True, choices=[('1', '在用'), ('0', '已报废')], max_length=2, null=True, verbose_name='使用情况'),
        ),
    ]
