# Generated by Django 4.2.8 on 2025-04-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0015_systerms_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systerms',
            name='use',
            field=models.CharField(choices=[('1', '在用'), ('0', '已报废')], default='1', max_length=2, verbose_name='使用情况'),
        ),
    ]
