# Generated by Django 4.2.8 on 2025-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0016_alter_systerms_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('A', '弱电间'), ('B', '弱点机柜')], default='A', max_length=2, verbose_name='弱电间/机柜'),
        ),
        migrations.AlterField(
            model_name='systerms',
            name='use',
            field=models.CharField(choices=[('1', '在用'), ('0', '已报废'), ('2', '测试'), ('3', '测试过')], default='1', max_length=2, verbose_name='使用情况'),
        ),
    ]
