# Generated by Django 4.2.8 on 2025-04-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0017_rooms_room_type_alter_systerms_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=7, unique=True, verbose_name='号码')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('tc', models.CharField(max_length=10, verbose_name='套餐')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '电话表',
                'verbose_name_plural': '电话表',
                'db_table': 'tel',
            },
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('A', '弱电间'), ('B', '弱电机柜')], default='A', max_length=2, verbose_name='弱电间/机柜'),
        ),
    ]
