# Generated by Django 4.2.8 on 2025-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0018_telephone_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='hb',
            field=models.CharField(default='d单独付费', max_length=20, verbose_name='合并付费组'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telephone',
            name='tc',
            field=models.CharField(max_length=20, verbose_name='套餐'),
        ),
        migrations.AlterModelTable(
            name='telephone',
            table='TEL',
        ),
    ]
