# Generated by Django 4.2.8 on 2025-04-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0019_telephone_hb_alter_telephone_tc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='guanjing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('location1', models.CharField(max_length=100, verbose_name='经度')),
                ('location2', models.CharField(max_length=100, verbose_name='纬度')),
                ('info', models.CharField(max_length=600, verbose_name='位置描述')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guanjing_campus', to='web_source.campus', verbose_name='校区')),
            ],
            options={
                'verbose_name': '弱电管井表',
                'verbose_name_plural': '弱电管井表',
                'db_table': 'GUANJING',
            },
        ),
    ]
