# Generated by Django 4.2.8 on 2025-04-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0020_guanjing'),
    ]

    operations = [
        migrations.AddField(
            model_name='guanjing',
            name='leixing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guanjing_dic', to='web_source.dic', verbose_name='类型'),
        ),
    ]
