# Generated by Django 4.2.8 on 2025-04-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0021_guanjing_leixing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guanjing',
            old_name='leixing',
            new_name='dic_guanjing',
        ),
    ]
