# Generated by Django 4.2.8 on 2025-04-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0022_rename_leixing_guanjing_dic_guanjing'),
    ]

    operations = [
        migrations.CreateModel(
            name='lujing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('points', models.TextField(verbose_name='途经点')),
                ('info', models.CharField(max_length=200, verbose_name='位置描述（哪到哪）')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '光缆路径表',
                'verbose_name_plural': '光缆路径表',
                'db_table': 'LUJING',
            },
        ),
    ]
