# Generated by Django 4.2.8 on 2025-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0023_lujing'),
    ]

    operations = [
        migrations.AddField(
            model_name='lujing',
            name='g',
            field=models.IntegerField(default=1, verbose_name='根数'),
        ),
        migrations.AddField(
            model_name='lujing',
            name='z',
            field=models.IntegerField(default=0, verbose_name='总芯数'),
        ),
        migrations.AddField(
            model_name='lujing',
            name='zt',
            field=models.JSONField(null=True, verbose_name='芯状态'),
        ),
    ]
