# Generated by Django 4.2.8 on 2025-04-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0024_lujing_g_lujing_z_lujing_zt'),
    ]

    operations = [
        migrations.AddField(
            model_name='guanjing',
            name='img',
            field=models.ImageField(default='', upload_to='guanjing/', verbose_name='水印图片'),
        ),
    ]
