# Generated by Django 4.2.8 on 2025-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0025_guanjing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guanjing',
            name='img',
            field=models.ImageField(default=[{}], upload_to='guanjing/', verbose_name='水印图片'),
        ),
    ]
