# Generated by Django 4.2.7 on 2025-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0026_alter_guanjing_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='systerms',
            name='wlj',
            field=models.BooleanField(default=False, verbose_name='物理服务器'),
        ),
    ]
