# Generated by Django 4.2.7 on 2025-12-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_source', '0027_systerms_wlj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnet',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vlan_ipnet', to='web_source.vlan', verbose_name='所属Vlan'),
        ),
    ]
